name: ci

on: [push]

jobs:

  publish:

    runs-on: ubuntu-latest
    name: Publish Charts
    if: gitea.event_name == 'push' && (gitea.ref == 'refs/heads/main' || startsWith(gitea.ref, 'refs/tags/'))

    steps:
      - uses: actions/checkout@v4
        with: 
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - uses: azure/setup-helm@v4.2.0

      - name: Package Chart
        run: helm package -u charts/selector

      - name: Push Chart
        run: curl --user ${{ secrets.REPO_USERNAME }}:${{ secrets.REPO_TOKEN }} -X POST --upload-file ./selector-*.tgz https://gitea.sheep-ghoul.ts.net/api/packages/${{ secrets.REPO_USERNAME }}/helm/api/charts
