apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "webapp.fullname" . }}-appsettings"
  namespace: {{ include "webapp.namespace" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Trace",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "Selector": {
        "ClientId": "{{ .Values.spotify.clientId }}",
        "ClientSecret": "{{ .Values.spotify.clientSecret }}",
        "SpotifyCallback": "{{ .Values.spotify.spotifyCallback }}",
        "LastfmClient": "{{ .Values.lastfmClient }}",
        "Redis": {
          "enabled": {{ .Values.redis.enabled }},
          "connectionstring": "{{ .Values.redis.connectionString }}"
        },
        "Now": {
          "ArtistResampleWindow": "14.00:00:00",
          "AlbumResampleWindow": "14.00:00:00",
          "TrackResampleWindow": "14.00:00:00"
        }
      },
      "Jwt": {
        "Issuer": "{{ .Values.jwt.issuer }}",
        "Audience": "{{ .Values.jwt.audience }}",
        "Key": "{{ .Values.jwt.key }}"
      },
      "ConnectionStrings": {
        "Default": "{{ .Values.databaseConnectionString }}"
      },
      "AllowedHosts": "*"
    }